service:
  name: time-tracker-code
frameworkVersion: '>=1.0.0 <2.0.0'
provider:
  name: aws
  runtime: nodejs12.x
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._\\'\",\\-\\/\\(\\)]+?)}}"
  stage: ${{opt:stage}} # Must use CLI option.
  region: ${{opt:region}} # Default region.
  cfLogs: true
  tracing: false
  versionFunctions: false
  iamRoleStatements: ${{file(serverless/resources/iamRoleStatements.yml)}}
  environment: ${{file(serverless/config/environment.yml)}}
  timeout: 30
  logRetentionInDays: 90
  deploymentBucket:
    name: time-tracker-deployment-${{self:provider.stage}}
custom: ${{file(serverless/config/custom_${{self:provider.stage}}.yml)}}
resources: ${{file(serverless/resources/resources.yml)}}
functions: ${{file(serverless/resources/lambdas.yml)}}
package:
  individually: false