timeBotUserPool:
  Type: 'AWS::Cognito::UserPool'
  Properties:
    AccountRecoverySetting:
      RecoveryMechanisms:
        - Name: verified_email
          Priority: 1
    AdminCreateUserConfig:
      AllowAdminCreateUserOnly: false
      UnusedAccountValidityDays: 90
    AutoVerifiedAttributes:
      - email
    EmailVerificationMessage: Welcome to Time Bot! Your verification code is {####}
    EmailVerificationSubject: Verification Code for Time Bot
    MfaConfiguration: OFF
    Policies:
      PasswordPolicy:
        MinimumLength: 8
        RequireLowercase: true
        RequireNumbers: true
        RequireSymbols: true
        RequireUppercase: true
    Schema:
      - Name: email
        AttributeDataType: String
        Required: true
      - Name: family_name
        AttributeDataType: String
        Required: true
      - Name: given_name
        AttributeDataType: String
        Required: true
    UsernameAttributes:
      - email
    UserPoolName: ${{self:provider.environment.TIME_BOT_USER_POOL_NAME}}

timeBotUserPoolDomain:
  Type: 'AWS::Cognito::UserPoolDomain'
  Properties:
    Domain: alexa-time-bot
    UserPoolId:
      Ref: timeBotUserPool

timeBotUserPoolAppClient:
  Type: 'AWS::Cognito::UserPoolClient'
  Properties:
    AllowedOAuthFlows:
      - code
    AllowedOAuthFlowsUserPoolClient: true
    AllowedOAuthScopes:
      - email
      - openid
      - aws.cognito.signin.user.admin
      - profile
    CallbackURLs:
      - https://alexa.amazon.co.jp/api/skill/link/M1PLPGT5AI83Q7
      - https://pitangui.amazon.com/api/skill/link/M1PLPGT5AI83Q7
      - https://layla.amazon.com/api/skill/link/M1PLPGT5AI83Q7
    ClientName: ${{self:provider.environment.TIME_BOT_APP_CLIENT_NAME}}
    GenerateSecret: true
    RefreshTokenValidity: 3650
    SupportedIdentityProviders:
      - COGNITO
    UserPoolId:
      Ref: timeBotUserPool
